### ISSUE TITLE
passing  versus dispatch

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#29]
In the architecture, player based events are "passed", while application based events are dispatched (with two different modes, that the application can subscribe to), two things should be clarified

1. what is the difference between dispatching to application and passing to player  ? 
2. how are events passed to player ? would there also be different modes for passing player events or is this irrelevant ? 

It would be nice if this could be clarified further

**Comment by irajs** [comment]
good point. the description needed an update.  Since all events go through the dispatch module,  now it reads as the following:

1. DASH Player processes the MPD. If the manifest includes any MPD Events, it parses them and appends them to Event & Timed Metadata Buffer.

2. Based on the MPD, DASH Player manages fetching and parsing the Segments before appending them to Media Buffer.

3. Parsing a Segment includes:
    
    1. Parse the high-level boxes such as Segment Index (sidx) and Event Message boxes, and append Event Message boxes to the Event & Metadata Buffer.
    2. For an Application-related timed metadata track, extracting the data samples, and appending them to Event & Metadata Buffer.
    3. For media segments, parse the segments and append them to Media Buffer.

4. Event & Metadata Buffer is a FIFO buffer, passing the events and timed metadata samples to Event & Metadata Synchronizer and Dispatcher function.

5. The DASH Player-specific Events are dispatched to DASH Player's Control, Selection & Heuristic Logic, while the Application-related Events and timed metadata track samples are dispatched to Application as the following. If an Application is subscribed to a specific Event or timed metadata stream, dispatch the corresponding event instances or timed metadata samples, according to the dispatch mode:
    1. For [=on-receive=] dispatch mode, dispatch the Event information or timed metadata samples as soon as they are received(or no later than <var>AT</var>).
    2. For [=on-start=] dispatch mode, dispatch the Event information or timed metadata samples at their associated presentation time, using the synchronization signal from the media decoder.

**Comment by RufaelDev** [comment]
So one remaining question, for DASH player specific events, the dispatch mode will be defined how ? As it is an internal interface it may not be that important or normative, but in this case the "application" cannot decide on this. For consistency of the buffer implementation, it may be good to use/recommend the same api/interface internally as is used by the application, hence the dash player can also choose the dispatch mode ? Otherwise it could also be explicitly stated that the dispatch mode for player events is not defined and implementation specific?

**Comment by haudiobe** [comment]
(Event TF 2019/06/14) if no additional comments by next Event call, this will be closed automatically.

**Comment by irajs** [comment]
Updated Figure 1 and the process to include the application subscription to events/timed metadata with desired dispatch mode.
