### ISSUE TITLE
terms definitions

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#37]
The document contains a lot of overlapping terms definitions, it would be good to clean that up and have terminology cleanly defined and used

**Comment by irajs** [comment]
Please identify the overlapping terms. 

(I tried to have clear terms, but perhaps I missed it. But still we use a lot of generic terms (presentation time, offset, ...) to describe different notions.)

**Comment by RufaelDev** [comment]
https://dashif-documents.azurewebsites.net/Events/master/event.html#index-defined-here

for example presentation time offset was define multiple times is it necessary? 

If it is not important this issue can be closed

**Comment by irajs** [comment]
The reason for having similar terms is that MPEG DASH spec have multiple variables with similar names, e.g. Event@presentationTime vs presentation_time parameter in emsg. 

In order to make them distinguishable, all similar attributes are defined with their elements. All terms from MPEG DASH spec are have external references.

**Comment by irajs** [comment]
(Event TF) we check again by IOP call next week if any improvement is needed.
