### ISSUE TITLE
Comments on Clause 2.3

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Events#48]
https://dashif-documents.azurewebsites.net/Events/master/event.html#mpd-event-timing

_The table should not be copied. And it needs to be aligned with the latest 4th edition._

As is shown in Figure 3, each MPD Event has three associated timing parameters along the media timeline:

_It is unclear on what is expressed here._

The PeriodStart Time (AT) of the Period element containing the EventStream element.

_What does this mean? Again we need to define the presentation relative to the start of the Period._

_How are the other parameters mapped to the structure?_

**Comment by irajs** [comment]
Referencing 4th edition is a good idea.

The anchor for Event streams are Period Start time, so each event presentation time is calculated using this reference.

Since when a DASH client parses a MPD period, it gets all the EventStream/Event elements, the AT of those events are the parsing time of the MPD, which is not later than Period Start time.

**Comment by irajs** [comment]
updated with 4th edition tables.

Missing text which was accidentally removed is back in, and hopefully addresses the question.

**Comment by haudiobe** [comment]
(Event TF - 19/10/04) Check implementation, if no further comments, will closed at next Event TF.
