### ISSUE TITLE
Need change Event @id to mandatory 

### ISSUE THREAD

**Issue by AUGxhub** [Dash-Industry-Forum/Events#76]
in 5.10.2.2 
the @id for Event is optional , 

is there some special reason let it not mandatory ?

saber.huang@samsung.com

**Comment by irajs** [comment]
The MPEG DASH specification allows the optional @id for MPD events. 

@id is mainly used for detecting repeating (equivalent) events. If the event instances are not being repeated, not inserting the id makes it simple, since the author doesn't need to make sure that @id is unique, especially if there is a possibility for other actors in the system including also event instances.

On the client side, any event instance without @id is a unique event instance, and it has to be processed. The client needs to make sure that the events without id are treated correctly.

Do you think the above model is too complex and mandating id (for MPEG@Events will simplify the client processing?

**Comment by AUGxhub** [comment]
how about event without @id  but repteaed , 
or does spec doesn't allow this cases ?

**Comment by irajs** [comment]
> how about event without @id but repteaed ,
> or does spec doesn't allow this cases ?

[Event TF 9/16]
3 options:
1. Mandating @id for MPD@type=dynamic
2. Mandating @id for all MPD evnets
3. Leave it as it is (optional) and the client has to process it. We can recommend that the author should be mindful of repeating events without id.

Recommendation: e think the 3rd option, not mandating it is the best solution. We will add a clause in Part 10 that authoring Event without @id will cause the client to dispatch every single instance of events and therefore repeating such events should be avoided.
